on:
  push:
    branches:
      - main
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    

    - name: ğŸ“¦ Instalar dependÃªncias npm
      run: npm install

    - name: ğŸ”¢ Gerar versÃ£o do WhatsFloat.js
      run: node build-script.js

    - name: ğŸ“‚ Sync arquivos do public na raiz do FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: whatsfloat-js.rocket.srv.br/
        local-dir: ./public/
        include: |
          *
        exclude: |
          **/node_modules/**
          **/.git*/**
          **/.vscode/**

    - name: ğŸ“‚ Sync pasta assets
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: whatsfloat-js.rocket.srv.br/assets/
        local-dir: ./assets/
        include: |
          **
        exclude: |
          **/node_modules/**
          **/.git*/**
          **/.vscode/**
